services:
  - type: web
    name: talktalk-backend
    runtime: docker
    plan: free
    region: singapore
    branch: master
    autoDeploy: true
    envVars:
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
